### ISSUE TITLE
laravel flash

### ISSUE THREAD

**Issue by ghahabib** [PaoloCentomani/Laravel-Boilerplate#3]
Hi,
ParseError
syntax error, unexpected 'Session' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

::Composer\Autoload\includeFile
C:\wamp64\www\laravel\laravel-vuejs.com-master\vendor\spatie\laravel-flash\src\Flash.php:13

<?php

 

namespace Spatie\Flash;

 

use Illuminate\Contracts\Session\Session;

use Illuminate\Support\Traits\Macroable;

 

/** @mixin \Spatie\Flash\Message */

class Flash

{

    use Macroable;

 

**protected Session $session;**

![2020-04-06_101129](https://user-images.githubusercontent.com/38330747/78531901-01d75600-77ef-11ea-8928-aef1940de339.jpg)

**Comment by PaoloCentomani** [comment]
spatie/laravel-flash requires PHP 7.4+

**Comment by ghahabib** [comment]
Thanks.
:)
